// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmHu1q6AE5l1rOrpjCeMga0uKF9PuCNpw',
    appId: '1:582462848951:web:dec909b6f30806d4baf232',
    messagingSenderId: '582462848951',
    projectId: 'aicamera-5bf95',
    authDomain: 'aicamera-5bf95.firebaseapp.com',
    storageBucket: 'aicamera-5bf95.appspot.com',
    measurementId: 'G-LRJK4EESDZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCQ8zFYaPGk6EjSaFB4tsgNSm90rDniCE',
    appId: '1:582462848951:android:80bda5a42ba4a72ebaf232',
    messagingSenderId: '582462848951',
    projectId: 'aicamera-5bf95',
    storageBucket: 'aicamera-5bf95.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtQh3yr48Qbz4LRt-W0clYg__1DmbgCiQ',
    appId: '1:582462848951:ios:ab15668416b73701baf232',
    messagingSenderId: '582462848951',
    projectId: 'aicamera-5bf95',
    storageBucket: 'aicamera-5bf95.appspot.com',
    iosClientId: '582462848951-4ldmnnucv6q7e7m0h8rm7gljhr8vv29k.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiCamera',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtQh3yr48Qbz4LRt-W0clYg__1DmbgCiQ',
    appId: '1:582462848951:ios:ab15668416b73701baf232',
    messagingSenderId: '582462848951',
    projectId: 'aicamera-5bf95',
    storageBucket: 'aicamera-5bf95.appspot.com',
    iosClientId: '582462848951-4ldmnnucv6q7e7m0h8rm7gljhr8vv29k.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiCamera',
  );
}
